name: tunetrend-workspace

version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: tunetrend-postgres-db
    labels:
      - "maintainer=Pdouvch"
      - "project.name=TuneTrend"
      - "project.environment=development"
      - "description=PostgreSQL Database for TuneTrend Backend API"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: tunetrend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    labels:
      - "owner=Pdouvch"
      - "project=TuneTrend"
