// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contact": {
            "post": {
                "description": "รับข้อความจากผู้ใช้พร้อมช่องทางติดต่อกลับ (อีเมลหรือเบอร์โทรไทย) บันทึกลงฐานข้อมูลและส่งอีเมลแจ้งเตือนผู้พัฒนา",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contact"
                ],
                "summary": "ส่งข้อความติดต่อถึงผู้พัฒนา",
                "parameters": [
                    {
                        "description": "ข้อมูลฟอร์มติดต่อ",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http.ContactRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ส่งข้อความสำเร็จ",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "ข้อมูลไม่ถูกต้อง เช่น เบอร์โทรไม่ใช่รูปแบบไทย",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "429": {
                        "description": "ส่งคำขอถี่เกินไป",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "เกิดข้อผิดพลาดที่เซิร์ฟเวอร์",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/trends": {
            "get": {
                "description": "ดึงข้อมูลเพลงเทรนด์ดิ้งตามรหัสประเทศ (เช่น TH, US) จากฐานข้อมูล",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Songs"
                ],
                "summary": "ดึงข้อมูลเพลงฮิต",
                "parameters": [
                    {
                        "type": "string",
                        "description": "รหัสประเทศ (Default: TH)",
                        "name": "country",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "คืนค่ารายการเพลงฮิต",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "เกิดข้อผิดพลาดที่เซิร์ฟเวอร์",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/trends/mv": {
            "get": {
                "description": "คัดกรองเฉพาะเทรนด์เพลงที่ระบบ AI วิเคราะห์ว่าเป็น Official Music Video",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Songs"
                ],
                "summary": "ดึงเฉพาะคลิป Official MV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "รหัสประเทศ (Default: TH)",
                        "name": "country",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "คืนค่ารายการ MV",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/trends/new": {
            "get": {
                "description": "คัดกรองเฉพาะเพลงเทรนด์ดิ้งที่เพิ่งปล่อยออกมาภายใน 7 วันที่ผ่านมา",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Songs"
                ],
                "summary": "ดึงเพลงฮิตมาใหม่ (ไม่เกิน 7 วัน)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "รหัสประเทศ (Default: TH)",
                        "name": "country",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "คืนค่ารายการเพลงใหม่",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_delivery_http.ContactRequest": {
            "type": "object",
            "properties": {
                "contactEmail": {
                    "type": "string"
                },
                "contactPhone": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "website": {
                    "description": "Website คือ honeypot field — ต้องซ่อนไว้ฝั่ง client (CSS/aria-hidden)\nผู้ใช้จริงต้องไม่มีทางกรอกค่านี้ ถ้ามีค่าแปลว่าเป็นบอท",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TuneTrend API",
	Description:      "Backend Service สำหรับดึงข้อมูลเทรนด์เพลงฮิตจาก YouTube",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
