name: tunetrend_mobile
description: "Trending YouTube Music videos by country."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  google_fonts: ^6.2.0
  intl: ^0.20.3
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.0
  youtube_player_iframe: ^6.0.2
  showcaseview: ^5.1.0
  share_plus: ^13.3.0
  firebase_core: ^4.14.0
  firebase_crashlytics: ^5.3.0
  firebase_remote_config: ^6.6.0
  firebase_analytics: ^12.5.0
  firebase_performance: ^0.11.5
  firebase_performance_dio: ^0.7.1
  dio: ^5.11.0
  cached_network_image: ^3.4.1
  shimmer: ^4.0.0
  package_info_plus: ^10.2.1
  firebase_messaging: ^16.6.0
  flutter_local_notifications: ^22.3.0
  lottie: ^3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#ff7a47"

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/lottie/
    - shorebird.yaml

