org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false

tunetrend.compileSdkVersion=36
tunetrend.minSdkVersion=24
tunetrend.targetSdkVersion=36
tunetrend.ndkVersion=28.2.13676358
